### ISSUE TITLE
grub2-install: error: efibootmgr failed to register the boot entry: Unknown error 19559280

### ISSUE THREAD

**Issue by tpgxyz** [rhboot/efibootmgr#100]
I have this issue with efibootmgr-16

```
19:42:13 [6]: Starting job "bootloader" 
19:42:13 [6]: Job file "/usr/lib64/calamares/modules/bootloader/main.py" 
19:42:13 [6]: Job description from __doc__ "bootloader" = "Starts procedure and passes 'fw_type' to other routine." 
19:42:13 [6]: [PYTHON JOB]:  "Bootloader: grub (efi)" 
19:42:13 [6]: Running "chroot" ("/tmp/calamares-root-swpv6s6n", "grub2-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=openmandriva", "--force") 
19:42:15 [6]: Finished. Exit code: 1 
19:42:15 [6]: Target cmd: ("grub2-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=openmandriva", "--force") 
19:42:15 [6]: Target output:
Installing for x86_64-efi platform.
grub2-install: error: efibootmgr failed to register the boot entry: Unknown error 19559280.
19:42:15 [6]: Python Error:
 <class 'subprocess.CalledProcessError'> 
 Installing for x86_64-efi platform.
grub2-install: error: efibootmgr failed to register the boot entry: Unknown error 19559280. 
 File "/usr/lib64/calamares/modules/bootloader/main.py", line 420, in run
    prepare_bootloader(fw_type)

  File "/usr/lib64/calamares/modules/bootloader/main.py", line 387, in prepare_bootloader
    install_grub(efi_directory, fw_type)

  File "/usr/lib64/calamares/modules/bootloader/main.py", line 261, in install_grub
    "--force"])

  File "<string>", line 5, in <module> 
 
19:42:15 [6]: Skipping non-emergency job "packages" 
```

**Comment by paulmenzel** [comment]
I am having the same problem with a Dell OptiPlex 7010 running Debian Sid/unstable with efibootmgr 15.

    error: efibootmgr failed to register the boot entry: Unknown error 21845.

Note, the error code is different each time.

Additionally, the system suspends afterward.

**Comment by tpgxyz** [comment]
@paulmenzel we fixed it this way
https://github.com/OpenMandrivaAssociation/grub2/blob/master/0001-Revert-Make-grub-install-check-for-errors-from-efibo.patch

**Comment by paulmenzel** [comment]
On 10/23/18 13:44, Tomasz Paweł Gajc wrote:
> @paulmenzel we fixed it this way
> https://github.com/OpenMandrivaAssociation/grub2/blob/master/0001-Revert-Make-grub-install-check-for-errors-from-efibo.patch

Thank you for the pointer. That would indeed work around the issue.

But, it’d be great to debug the efibootmgr issue.

Is there an easy way, for example with strace, to get the efibootmgr
commands with arguments that is executed by `grub-install`? I tried

    sudo strace -v -f -e execve -s10000 grub-install /dev/sda

but only got the output below.

    [pid 27032] execve("/bin/efibootmgr", ["efibootmgr"], ["LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:", "LANG=en_US.UTF-8", "DISPLAY=localhost:10.0", "TERM=xterm-256color", "LANGUAGE=en_US:en", "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "MAIL=/var/mail/root", "LOGNAME=root", "USER=root", "USERNAME=root", "HOME=/root", "SHELL=/bin/bash", "SUDO_COMMAND=/usr/bin/strace -v -f -e execve -s10000 grub-install /dev/sda", "SUDO_USER=joey", "SUDO_UID=1000", "SUDO_GID=1000", "LC_ALL=C"]) = 0
    [pid 27032] +++ exited with 0 +++
    --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=27032, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
    grub-install: error: efibootmgr failed to register the boot entry: Unknown error 22020.
