### ISSUE TITLE
efibootmgr shows nothing

### ISSUE THREAD

**Issue by sebma** [rhboot/efibootmgr#102]
Hi,

My `efibootmgr` shows nothing. Although I remember It used print the EFI boot entries.

I'm using the version package along with Ubuntu 14.04 : v0.5.4

I do understand it's an old version, however, do you have any clew why efibootmgr is not showing anything ?

**Comment by vathpela** [comment]
Usually this means you've switched the system firmware into BIOS mode?  Aside from that, if neither /sys/firmware/efi/efivars nor /sys/firmware/efi/vars is mounted, it won't believe it's an EFI machine.

**Comment by sebma** [comment]
No, it is not in BIOS mode because the `/sys/firmware/efi` directory is present : 
```
$ ls -l /sys/firmware/efi
total 0
-r--r--r--  1 root root 4096 mars   7 11:42 config_table
drwxr-xr-x  2 root root    0 févr. 27 13:15 efivars/
-r--r--r--  1 root root 4096 mars   7 11:42 fw_platform_size
-r--r--r--  1 root root 4096 mars   7 11:42 fw_vendor
-r--r--r--  1 root root 4096 mars   7 11:42 runtime
drwxr-xr-x 12 root root    0 mars   7 11:42 runtime-map/
-r--------  1 root root 4096 mars   6 17:31 systab
drwxr-xr-x 71 root root    0 mars   7 11:41 vars/
```

`/sys/firmware/efi/efivars` is mounted but `/sys/firmware/efi/vars` is not mounted : 
```
$ df /sys/firmware/efi/efivars/ /sys/firmware/efi/vars/
Filesystem     Type      Size  Used Avail Use% Mounted on
none           efivarfs     0     0     0    - /sys/firmware/efi/efivars
sysfs          sysfs        0     0     0    - /sys
$ efibootmgr 
$ echo $?
0
```

How can I fix this ?
