### ISSUE TITLE
efibootmgr -o does nothing

### ISSUE THREAD

**Issue by solsticedhiver** [rhboot/efibootmgr#103]
Apparently using **efibootmgr** v15 or v16 to reorder EFI boot entries does nothing.

I tried with efibootmgr 15 on ubuntu 18.10. Changed the boot order with

    efibootmgr -o 0003,0002,2001

efibootmgr shows it's OK. Another call to efibootmgr shows the correct order set.
But on the next boot, the previous order is still used as if nothing has been changed.

The same happened using efibootmgr 16 on archlinux.

On a DELL inspiron 15 (3525).

I had to change the boot order in the EFI (aka BIOS) firmware menu.

Is it efibootmgr or the EFI firmware at fault ? o somehting else ?

**Comment by porssimies** [comment]
I have the same problem in Debian 9.6
Unfornately I do not have a change to change EFI menu in my BIOS pages.

**Comment by vathpela** [comment]
If another call to efibootmgr shows the order you set, then either the kernel or firmware isn't correctly relating that the call to set the variable failed, and there's nothing we can really do about it.
