### ISSUE TITLE
How to add entry to MBR shadow ?

### ISSUE THREAD

**Issue by ranshalit** [rhboot/efibootmgr#104]
Hello,

I am trying to add boot entry for MBR table (shadow) in SSD.
using bcfg it is possible to browse to device fs0:\EFI\boot\bootx64.efi (pressing tab will show all the device in current directory).
But we don't have bcfg in our BIOS.
I've tried to add the following:
1. efibootmgr -c -d /dev/sda -p 0 -L "mypba" -l "\EFI\boot\bootx64.efi"
and also the following
2. efibootmgr -c -d /dev/sda -p 0 -L "mypba" -l "\EFI\boot\bootx64.efi"
But in both cases the UIEFI boot fails to start.

Is it possible to find the device somehow (just as we browse the entry in UEFI shell with "ls" command and pressing tab) ?

Thank you for any idea,
Ran

**Comment by vathpela** [comment]
I don't understand what you're asking for.  The only way "add a boot entry for MBR table" makes sense to me is as a BIOS boot option, but then I don't understand why you're trying '-l "\EFI\boot\bootx64.efi"'.

If writing a "BIOS Boot" entry is what you mean, we don't currently support it, but I'd certainly be willing to review patches.

**Comment by ranshalit** [comment]
Hi,
It's old ticket, and eventually it did work.
So I assume that writing a "BIOS Boot" entry is already supported now and this ticket can be closed)
Thanks.
