### ISSUE TITLE
Feature request: Option for time-limited BootNext value

### ISSUE THREAD

**Issue by Klohto** [rhboot/efibootmgr#106]
**_Description of use case:_**
At [beaker-project](https://beaker-project.org/), we were tasked with an interesting issue - [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1455763). 
If someone is testing, for instance, that **kdump** will crash, it's obviously not possible to restart the system. Therefore setting the BootNext value is necessary. But problem arise when the testing fails and system doesn't crash as it should.
We are then stuck with a machine that on next testing of someone else task will be unusable, since: 

1. its not going to boot from netboot, as we require
2. someone will have to go and fix it

While all of this is possible at our side by adding a simple timer I was surprised that nobody needed this option before in **efibootmgr**.

**_Solution:_**
Add an optional parameter specifying time slot, in seconds, for when the BootNext value is valid.
After the specified time passes, clear the BootNext value.

Example: `efibootmgr -n 0001 180` - _BootNext valid for 180 seconds_

**Comment by vathpela** [comment]
The firmware is responsible for interpreting and removing BootNext, so this isn't really something we can do from efibootmgr.  The thing to do here is either a) change your tests to remove BootNext in these cases, or b) create another variable that includes a timestamp to compare to, and then make the bootloader stack you're using during the later network boot able to make decisions by interpreting that variable.

We *can* work with you to enable grub to find such a variable and chain-load to some other boot entry, but it's going to require something a lot newer than the grub-0.97 being deployed in that bz.
