### ISSUE TITLE
Minor mistake @ man page

### ISSUE THREAD

**Issue by Stamoulohta** [rhboot/efibootmgr#111]
At "Creating a new boot option" section of man page:
'/boot/efi' is assumed to be the EFI System Partition and '/dev/sda1' is assumed to be the mount point. I guess they should be reversed.

**Comment by rbisewski** [comment]
A nice find; I have since adjusted various docs in that repo and have made a pull request.

**Comment by vathpela** [comment]
(I think this was fixed when I pulled @rbisewski's branch; if it's not, please re-open this.)
