### ISSUE TITLE
--create(d) entry not saved after reboot

### ISSUE THREAD

**Issue by bphd** [rhboot/efibootmgr#135]
Back in time I created an entry to boot to an vmlinuz and it worked fine since a long time

But now I unplugged my drives and booted and this entry was gone

I replugged my drives, tried to recreate my entry like before but now the entry does not stay after reboot, I don't see it in UEFI

**Comment by martinezjavier** [comment]
This is likely a problem with your firmware and not efibootmgr. I'm closing this.
