### ISSUE TITLE
Properly tag release 17 in GitHub

### ISSUE THREAD

**Issue by paulmenzel** [rhboot/efibootmgr#139]
On the [GitHub project page](https://github.com/rhboot/efibootmgr), release 16 is still shown as the latest release. On the [release page](https://github.com/rhboot/efibootmgr/releases) release 17 also looks different than 16.

**Comment by frozencemetery** [comment]
The tag was made properly, but it hadn't been turned into a github-ified release with artifact.  Fixed now.
