### ISSUE TITLE
Better way to identify entries

### ISSUE THREAD

**Issue by eoli3n** [rhboot/efibootmgr#141]
Here what I need to do to automate boot order with a dynamic entry selection

```
efibootmgr -o "$(efibootmgr | awk -F'*' '/IPV4/ {print substr($1,5,4)}'),$(efibootmgr | awk -F'*' '/ubuntu/ {print substr($1,5,4)}')"
```
I suggest, for exemple, to be able to set boot order with a string which match an entry, which would be way more simpler and dynamic.
```
efibootmgr -o "IPV4,ubuntu"
```

Why entries are prefixed with "Boot" if i can't use ``-o Boot0001`` ?

**Comment by eoli3n** [comment]
is there anybody here ?

**Comment by frozencemetery** [comment]
> Here what I need to do to automate boot order with a dynamic entry selection

Yeah, I can't immediately tell what this code is doing.  Can you explain what you're trying to do?

> is there anybody here ?

Open source project, reasonable patches welcome, etc.

**Comment by eoli3n** [comment]
> Can you explain what you're trying to do?

Please read the issue, its crystal clear.

> Open source project

As UEFI is now generalizing, this project is first-class citizen, and deserve **way more** work (not one year to read an issue).

**Comment by frozencemetery** [comment]
https://github.com/rhboot/efibootmgr/blob/main/CODE_OF_CONDUCT.md
