### ISSUE TITLE
[SOLVED] Unable to compile efibootmgr-17 against efivar-37 with gcc-11.2.0

### ISSUE THREAD

**Issue by chepati** [rhboot/efibootmgr#149]
make[3]: Leaving directory '/usr/src/build-x86_64/efibootmgr-17/src'
gcc   -O2 -mtune=core2 -pipe -fcommon -I/usr/src/build-x86_64/efibootmgr-17/src/include -Wall -Wextra -Wsign-compare -Wstrict-aliasing -std=gnu11 -fPIC -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DLOCALEDIR=\"/usr/share/locale/\" -DEFIBOOTMGR_VERSION="\"17\"" -DDEFAULT_LOADER=\"\\\\EFI\\\\/boot/EFI\\\\grub.efi\"   -I/usr/include//efivar  -c -o efi.o efi.c
gcc   -O2 -mtune=core2 -pipe -fcommon -I/usr/src/build-x86_64/efibootmgr-17/src/include -Wall -Wextra -Wsign-compare -Wstrict-aliasing -std=gnu11 -fPIC -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DLOCALEDIR=\"/usr/share/locale/\" -DEFIBOOTMGR_VERSION="\"17\"" -DDEFAULT_LOADER=\"\\\\EFI\\\\/boot/EFI\\\\grub.efi\"   -I/usr/include//efivar  -c -o unparse_path.o unparse_path.c
gcc   -O2 -mtune=core2 -pipe -fcommon -I/usr/src/build-x86_64/efibootmgr-17/src/include -Wall -Wextra -Wsign-compare -Wstrict-aliasing -std=gnu11 -fPIC -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DLOCALEDIR=\"/usr/share/locale/\" -DEFIBOOTMGR_VERSION="\"17\"" -DDEFAULT_LOADER=\"\\\\EFI\\\\/boot/EFI\\\\grub.efi\"   -I/usr/include//efivar  -c -o efibootdump.o efibootdump.c
efibootmgr.c: In function 'parse_opts':
efibootmgr.c:1541:36: error: conflicting types for 'efi_set_verbose'; have 'int(int,  FILE *)'
 1541 |                         extern int efi_set_verbose(int verbosity, FILE *errlog);
      |                                    ^~~~~~~~~~~~~~~
In file included from efibootmgr.c:49:
/usr/include//efivar/efivar.h:231:13: note: previous declaration of 'efi_set_verbose' with type 'void(int,  FILE *)'
  231 | extern void efi_set_verbose(int verbosity, FILE *errlog)
      |             ^~~~~~~~~~~~~~~
make[2]: *** [/usr/src/build-x86_64/efibootmgr-17/Make.rules:32: efibootmgr.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/usr/src/build-x86_64/efibootmgr-17/src'
make[1]: *** [Makefile:12: all] Error 2
make[1]: Leaving directory '/usr/src/build-x86_64/efibootmgr-17'
make: *** [efibootmgr:95: /usr/src/build-x86_64/../log-x86_64/base-efibootmgr-17] Error 2

**Comment by frozencemetery** [comment]
I believe this was fixed in https://github.com/rhboot/efibootmgr/commit/99b578501643377e0b1994b2a068b790d189d5ad - can you retry with a git version of efibootmgr?

**Comment by chepati** [comment]
Thanks @frozencemetery !  Applying that patch against v17 did indeed fix the compile failure.  Marking as solved.
