### ISSUE TITLE
[feature request] add support an JSON-formatted input and output

### ISSUE THREAD

**Issue by Bogdan107** [rhboot/efibootmgr#163]
# Intro
Options, which allows to use JSON-formatted input and output, allows to do an efficient machine-readable usage of efi boot manager.

## Proposal:
Add next options:
- **--json-in** - for ready JSON-formatted input
With this option, any other input options, which modify an efi entry, mus be ignored.
- **--json-out** - for write JSON-formatted output

Program must be ready to read value of _--json-in_ option from stdin.

### 1) Create entry:
```
efibootmgt --json-in {
  "create",
  "label":"refind",
  "device":"/dev/sda",
  "part":"1",
  "loader":"\EFI\refind\refind_x64.efi"
}
```
or another form to ready value from stdin:
```
echo {"create","label":"refind","device":"/dev/sda","part":"1", "loader":"\EFI\refind\refind_x64.efi"} | efibootmgt --json-in
```
### 2) Remove entry:
```
efibootmgr --json-in {"bootnum":"0001","delete-bootnum"}
```
### 3) Modify the label of an entry:
```
efibootmgr --json-in {"bootnum":"0001","label":"refind on the disk 1"}
```

## Bonus 1 - resolve issue #49
With _JSON-output_ and _JSON-input_ features, task to modify an label (#49) - is trivial.

To modify an label:
1) read binary data of an entry from efi variable;
2) decode binary data of boot entry into JSON-object;
3) modify JSON-entry in JSON-object;
4) encode JSON-object into binary data;
5) replace value of efi-variable with binary data.

In this order, only step 3 (modify attribute in JSON-object) - is a signle part, that can be executed outside the efibootmgr, after improving _--json-in_ and _--json-out_ options.

## Bonus 2 - split efibootmgr into 2 separate tools: efibootmgr and efibootmgr-cli
With this options, efibootmgr must support just this 5 operations:
- add new boot entry (create new efi variable as boot entry);
- read exist boot entry (read value of efi variable);
- write exist boot entry (replace value of efi variable);
- remove exist boot entry (delete efi variablle);
- modify boot attributes, which has effect for boot process.

Read and write operations can be calles as a proxy for _efivar_ tool, so _bootmgr_ tool may be an very simple tool, which just:
- create new boot entry;
- remove exist boot entry;
- modify boot attributes (boot order, boot timeout, etc).

All another operations to modify Boot entries may be moved outside - from the _efibootmgr_ tool into the **efibootmgr-cli** tool.
_efibootmgr-cli_ tool may be just a json-manipulation tool.
**efibootmgr-cli.py** - is a python script. In this form, script may have all featured functionality.
**efibootmgr-cli** - is a binary tool, which have most used operations in emergency situation to restore boot functionality of the system.

**Comment by frozencemetery** [comment]
Dup of #70.  Please search existing issues before opening new ones
