### ISSUE TITLE
Commit for release 18 not in this repository

### ISSUE THREAD

**Issue by dvzrv** [rhboot/efibootmgr#167]
Hi! I'm packaging efibootmgr for Arch Linux.

The [commit for release 18](https://github.com/rhboot/efibootmgr/tree/18) seems to be not part of this repository: "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

![screenshot-2022-07-09_09-51-46](https://user-images.githubusercontent.com/432519/178096995-f0051f30-2a10-4545-a3c6-3ad3964b88db.png)

**Comment by dvzrv** [comment]
Ah seems that commit was just never merged to the default branch and only exists in commit chain towards tag 18.

**Comment by frozencemetery** [comment]
Fixed now, thanks for reminder.
