### ISSUE TITLE
Doesn't work with 6.5 kernel on macbookpro13,1

### ISSUE THREAD

**Issue by xeron** [rhboot/efibootmgr#194]
So I was experimenting with Linux on macbookpro13,1. I know it might have weird Apple EFI but what I encountered is:

* `efibootmgr` works with 6.1 kernel
* `efibootmgr` doesn't work with 6.5 kernel, stating "EFI variables are not supported on this system"

But `/sys/firmware/efi/efivars` is present on both kernel versions.

On 6.5 `strace efibootmgr` shows something like this:
```
statfs("/sys/firmware/efi/efivars", ...) ... EINVAL ...
...("/sys/firmware/efi/vars") ... ENOENT (No such file or directory)
```

**Comment by xeron** [comment]
Seems like it's a [kernel bug](https://git.kernel.org/pub/scm/linux/kernel/git/efi/efi.git/commit/?h=urgent&id=79b83606abc778aa3cbee535b362ce905d0b9448).

**Comment by alexmyczko** [comment]
I have `MacBookPro17,1` and efibootmgr 18 also /sys/firmware/efi/efivars
but no luck, `EFI variables are not supported on this system.`

**Comment by xeron** [comment]
Try newer kernel. It was fixed at some point.
