### ISSUE TITLE
Error building efibootmgr with clang

### ISSUE THREAD

**Issue by slacka** [rhboot/efibootmgr#60]
Trying to build efibootmgr with clang results in:

`efivar.h:86:16: error: unknown attribute '__artificial__' ignored`

The full log of this error can be found here:
http://clang.debian.net/logs/2016-08-30/efibootmgr_0.12-4_unstable_clang.log

**Comment by vathpela** [comment]
Should be fixed with https://github.com/rhboot/efivar/commit/33e91badb9f0 .
