### ISSUE TITLE
Build with uClibc

### ISSUE THREAD

**Issue by andy-shev** [rhboot/efibootmgr#61]
Since I patched efivar to be built with uClibc (https://github.com/rhinstaller/efivar/issues/76), We can do the same for efibootmrg. Patch is here: https://github.com/andy-shev/efibootmgr/commit/bbfcc60497c326576bb23cb01d90115ef3cf6947

**Comment by andy-shev** [comment]
It would be nice if someone tell me how to test this for sure. Currently *ubootmrg* works perfectly in my environment, but it doesn't use Unicode characters.

**Comment by vathpela** [comment]
This is in master now.
