### ISSUE TITLE
Feature request: Swapping / reordering entries

### ISSUE THREAD

**Issue by rpm0372** [rhboot/efibootmgr#69]
Don't know if this is common, but when booting my GA-990FXA-UD5 mobo always displays entries in creation order rather than boot order.  For example (looking at my abridged -v output below) if I could swap entries Boot0002 and Boot0001 then I could have Kubuntu first on the list displayed at boot-time instead of my rarely-used EDK2 shell.

my (abridged) -v output:

BootOrder: 0002,0005,0004,0001
Boot0001* EDK2 Shell
Boot0002* Kubuntu 17.04
Boot0004* opensuse 42
Boot0005* Windows 10

**Comment by edrozenberg** [comment]
Yes, and it would be nice to be able to change the boot number for entries, such as renaming an item from Boot0003 to Boot0002.

**Comment by frozencemetery** [comment]
Seems like #126 is a dup of this.
