### ISSUE TITLE
"efibootmgr -v" says Could not read variable 'BootOrder' , 'BootNext' , 'BootCurrent' , etc : No such file or directory

### ISSUE THREAD

**Issue by P-PS** [rhboot/efibootmgr#73]
Hello,
I have a **lenovo G580-20157 laptop**, currently using **Ubuntu 17.04** and on this machine**( GPT Partitioned)**   the command " **root@sam:~# efibootmgr** " gives the following output: 
`root@sam:~# efibootmgr`
`Timeout: 0 seconds`
`No BootOrder is set; firmware will attempt recovery`

**Currently using the following version of efibootmgr**

`root@sam:~# efibootmgr -V`
` version 14
`
and also the command "**root@sam:~# efibootmgr -v -v** " gives the following output:

 `root@sam:~# efibootmgr -v -v`
`Could not read variable 'BootNext': No such file or directory
error trace:`
 `efivarfs.c:230 efivarfs_get_variable(): open(/sys/firmware/efi/efivars/BootNext-8be4df61-93ca-11d2-aa0d-00e098032b8c): No such file or directory`
` lib.c:145 efi_get_variable(): ops->get_variable failed: No such file or directory`
`Could not read variable 'BootCurrent': No such file or directory`
`error trace:`
` efivarfs.c:230 efivarfs_get_variable(): open(/sys/firmware/efi/efivars/BootCurrent-8be4df61-93ca-11d2-aa0d-00e098032b8c): No such file or directory`
` lib.c:145 efi_get_variable(): ops->get_variable failed: No such file or directory`
`Timeout: 0 seconds`
`Could not read variable 'BootOrder': No such file or directory`
`error trace:`
` efivarfs.c:230 efivarfs_get_variable(): open(/sys/firmware/efi/efivars/BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c): No such file or directory`
` lib.c:145 efi_get_variable(): ops->get_variable failed: No such file or directory`
` efibootmgr.c:363 read_order(): efi_get_variable failed: No such file or directory`
`No BootOrder is set; firmware will attempt recovery`
`Could not read variable 'MirrorCurrent': No such file or directory`
`error trace:`
 `efivarfs.c:230 efivarfs_get_variable(): open(/sys/firmware/efi/efivars/MirrorCurrent-7b9be2e0-e28a-4197-ad3e-32f062f9462c): No such file or directory`
` lib.c:145 efi_get_variable(): ops->get_variable failed: No such file or directory`
`Could not read variable 'MirrorRequest': No such file or directory`
`error trace:`
` efivarfs.c:230 efivarfs_get_variable(): open(/sys/firmware/efi/efivars/MirrorRequest-7b9be2e0-e28a-4197-ad3e-32f062f9462c): No such file or directory`
` lib.c:145 efi_get_variable(): ops->get_variable failed: No such file or directory`
`root@sam:~#
`
**Now as i konw from the output that the above command is searching for variables like BootNext , BootCurrent, BootOrder, etc. in the location " /sys/firmware/efi/efivars/ " so i reached there and found that there are some other variables too but not the above ones. 
So i want to ask that: Is this a bug in the efibootmgr command or anything else ? 
Also, what can be done on my part to sole this?**

**Comment by P-PS** [comment]
Here is a **strace** of the command  **efibootmgr -v** .
[efibootmgr_strace.txt](https://github.com/rhboot/efibootmgr/files/1100202/efibootmgr_strace.txt)

**Comment by gdamjan** [comment]
try updating the BIOS )well, the UEFI firmware really) on your hardware.

**Comment by P-PS** [comment]
I am already on the latest bios(released in year 2013) version provided by
Lenovo for G580-20157 laptop.

**Comment by vathpela** [comment]
Well, for reasons I don't know, I can't read your strace, but if there's other variables in  /sys/firmware/efi/efivars/ but not Boot#### variables or BootOrder, either a) there's actually no boot order set (which is pretty unlikely), or b) the firmware isn't correctly providing this to the kernel.

Unfortunately there's not much we can do about the second case.

**Comment by P-PS** [comment]
Vathpela is right with his second opinion.

Hey Everyone...
I have discovered a workaround to the above problem for my  laptop( lenovo G580, 20157).

Here, Once agian i am discribing what was my problem with "efibootmgr" command. 
On doing "efibootmgr -v" at terminal it always resulted in: " No BootOrder is set; firmware will attempt recovery" and nothing more or less than this as an output. And there were no BootOrder, Boot0000, B0001, etc. variables in /sys/firmware/efi/efivars folder.
Besides this my objective was also to access BIOS/UEFI setting or menu by pressing F2 or F12 key on my laptop.

Now the workaround is as follows:

1)I mounted "manjaro linux" iso file and copied "shellx64_v2.efi" file from the mounted manjaro "EFI" directory to my /boot/efi/ubuntu/ folder. And then created a boot loader like this: "# efibootmgr -c -b 000C -d /dev/sda -p 1 -L SHELL -l /EFI/ubuntu/shellx64_v2.efi". Now rebooted and i was having manjaro uefi shell before grub menu. There i played with it to understand what is it then i noticed that there are duplicate "SFRM_NVRAM" variable using "dmpstore SFRM_NVRAM -b" command at the shell. So i decided to flash bios to remove the duplicacy.

2) So i installed windows 8 on a different partition (having linux installed previously).

3) Re-flashed Bios with the same current version which i was having.

Note: If after installing windows only windows boots then using live linux usb media boot your machine and re-create loader for Manjaro shell file using the command discribed above to make it boot first.

4) After flashing bios the duplicate SFRM_NVRAM" was still there. So i decided to do a full back up every efi variable present on my machine using "dmpstore -s All_variable" and i also did a single single backup of each efi variable present there such as "dmpstore Boot0000 -s Boot0000_Setup" on my pendrive, so that i may restore them later using "dmpstore -l Boot0000_Setup".

5)I decided to manually delete SFRM_NVRAM using "dmpstore -d SFRM_NVRAM" command and it sayed deleted. But on the next reboot i checked for it and the duplicate variables were still there. Then after i exited the shell(uefi) using "exit"  and booted to ubuntu using the grub menu that came after that.

6) And there i once again checked for Boot#### variables in /sys/firmware/efi/efivars folder using "ls" and fortunately all the Boot#### variables was present there. And now the "efibootmgr -v" is also showing all the loaders variables(Boot####) and their respective paths.

After this  now i am able to access Bios/Uefi setting using F2 or F12 key. And also able to set bootorder, and able to run "fwsetup" command successfully at grub prompt.

Disclamer: If anyone finds this interesting then proceed only on your own risk. I will not be liable in any case for any damage caused to your laptop or pc.

**Comment by P-PS** [comment]
If anyone having same problem also solved it using  the method which i have described here then please share it with me.

**Comment by psychobacter** [comment]
@P-PS I already had the latest UEFI firmware installed so I opened the firmware settings and enabled back flash and flashed the latest bios update via Galdalf's win 10 PE. After flashing the update the the option to open bios menu is gone. Is there any way to fix this? I am currently using windows 10 on my laptop and sometimes when I start my PC my laptop shows a black scren for few seconds then the lenovo logo appears and then nothing happens. I have to restart my laptop to get windows 10 booted.

**Comment by tommatibag** [comment]
> Vathpela is right with his second opinion.
> 
> Hey Everyone...
> I have discovered a workaround to the above problem for my laptop( lenovo G580, 20157).
> 
> Here, Once agian i am discribing what was my problem with "efibootmgr" command.
> On doing "efibootmgr -v" at terminal it always resulted in: " No BootOrder is set; firmware will attempt recovery" and nothing more or less than this as an output. And there were no BootOrder, Boot0000, B0001, etc. variables in /sys/firmware/efi/efivars folder.
> Besides this my objective was also to access BIOS/UEFI setting or menu by pressing F2 or F12 key on my laptop.
> 
> Now the workaround is as follows:
> 
> 1. I  mounted "manjaro linux" iso file and copied "shellx64_v2.efi" file from the mounted manjaro "EFI" directory to my /boot/efi/EFI/ubuntu/ folder. And then created a boot loader like this: "# efibootmgr -c -b 000C -d /dev/sda -p 1 -L SHELL -l /EFI/ubuntu/shellx64_v2.efi". Now rebooted and i was having manjaro uefi shell before grub menu. There i played with it to understand what is it then i noticed that there are duplicate "SFRM_NVRAM" variable using "dmpstore SFRM_NVRAM -b" command at the shell. So i decided to flash bios to remove the duplicacy.
> 2. So i installed windows 8 on a different partition (having linux installed previously).
> 3. Re-flashed Bios with the same current version which i was having.
> 
> Note: If after installing windows only windows boots then using live linux usb media boot your machine and re-create loader for Manjaro shell file using the command discribed above to make it boot first.
> 
> 1. After flashing bios the duplicate SFRM_NVRAM" was still there. So i decided to do a full back up every efi variable present on my machine using "dmpstore -s All_variable" and i also did a single single backup of each efi variable present there such as "dmpstore Boot0000 -s Boot0000_Setup" on my pendrive, so that i may restore them later using "dmpstore -l Boot0000_Setup".
> 2. I decided to manually delete SFRM_NVRAM using "dmpstore -d SFRM_NVRAM" command and it sayed deleted. But on the next reboot i checked for it and the duplicate variables were still there. Then after i exited the shell(uefi) using "exit"  and booted to ubuntu using the grub menu that came after that.
> 3. And there i once again checked for Boot#### variables in /sys/firmware/efi/efivars folder using "ls" and fortunately all the Boot#### variables was present there. And now the "efibootmgr -v" is also showing all the loaders variables(Boot####) and their respective paths.
> 
> After this now i am able to access Bios/Uefi setting using F2 or F12 key. And also able to set bootorder using "efibootmgr" and also able to run "fwsetup" command successfully at grub prompt.
> 
> My Conclusion: According to my observation i can say that it is absolutly a firmware bug which is the cause of all the evil thing. So a BIOS/UEFI update may solve the issue.
> 
> Disclamer: If anyone finds this interesting then proceed only on your own risk. I will not be liable in any case for any damage caused to your laptop or pc.

Hi sir I have the same problem on my Lenovo g580 20157 and trying to understand your instructions I'm on the first instruction honestly I don't understand much(newbie) that's why I'll ask the simplest sentence(the last sentence).

Please how did you flashed your bios?
Can I use the 62cn44ww_64.exe bios?
I'm having problem since it's an exe file I tried searching on google for workaround on flashing:
*via Wine - Not recommended by other users
*via Bootable cd version then terminal - sadly lenovo haven't released for bootable :(

Patietly waiting for your feedback thanks :+1:

**Comment by P-PS** [comment]
First of all you should not mess with a very old machine ( Its a 2012Y  laptop model).
However if you want to update BIOS then get the latest bios version **62cn97ww_97.exe** from this [link](https://pcsupport.lenovo.com/in/en/products/laptops-and-netbooks/lenovo-g-series-laptops/lenovo-g580-notebook/downloads/driver-list/component?name=BIOS%2FUEFI) or Select Windows version 8 on lenovo support website not 8.1 .

And the only best way to flash BIOS is to install Windows (7 or 8) and then do  it. ( tedious task to just update BIOS ).

**Comment by tommatibag** [comment]
My bios current version in 62CN91WW - dated 10/23/2012

(If) When I updated it to 62cn97ww_97.exe do you think I can access again my bios settings using f2?

Thanks for the kind reply @P-PS appreciate it
