### ISSUE TITLE
RFE: Automatically (re-)mount efivarfs read/write when necessary

### ISSUE THREAD

**Issue by floppym** [rhboot/efibootmgr#76]
OpenRC is a service manager used mainly by Gentoo Linux and derived distros as an alternative to systemd. As of version 0.28, OpenRC mounts efivarfs read-only to prevent accidental damage to EFI variables.

https://gitweb.gentoo.org/proj/openrc.git/tree/NEWS.md?h=0.28

It would be helpful if efibootmgr would re-mount efivarfs read/write when it needs to make updates, and re-mount it read-only when the updates are complete. This would save the system administrator a couple of steps.

**Comment by hollaho** [comment]
I second this - ran into the same problem and the error message does not immediately point to any solution, so had to google what was going on...

**Comment by superm1** [comment]
As mentioned in other reports, the kernel now treats efivarfs as immutable (since 4.5-rc5: torvalds/linux@ed8b0de) .  It's not important to have processes manage remounting efivarfs as rw, they manage the immutable bit for each individual file.
