### ISSUE TITLE
Display binary data in a nicer way or trim

### ISSUE THREAD

**Issue by edrozenberg** [rhboot/efibootmgr#77]
Some of the boot option values set by my motherboard show as gibberish in ```efibootmgr -v```.  I'm assuming it's because those entries contain binary data.

It would be great if efibootmgr could display that data in a more user friendly way (unless the intent is to show the binary data as is for some purpose). Or otherwise to show only the data that makes sense to a user and not show the rest.

Example of what I'm seeing:

```$ efibootmgr -v```

```
BootCurrent: 0000
Timeout: 1 seconds
BootOrder: 0000,0001,0003,0005,0006,0007
Boot0000* ATA SSD 0	HD(1,800,32000,55d3dd6b-2477-4872-b74f-8ae77a473c84)File(\EFI\ATA SSD 0\grubx64.efi)
Boot0001* ATA SSD 1	HD(1,800,32000,cbd5f274-d461-430b-895b-9fc5d65caceb)File(\EFI\ATA SSD 1\grubx64.efi)
Boot0003* UEFI: Built-in EFI Shell	Vendor(5023b95c-db26-429b-a648-bd47664c8012,)..BO
Boot0005  Network Card	BIOS(6,0,00)..GO..NO........q.I.B.A. .G.E. .S.l.o.t. .0.5.0.0. .v.1.5.1.3.........................rN.D+..,.\...........B..Gd-.;.A..MQ..L.I.B.A. .G.E. .S.l.o.t. .0.5.0.0. .v.1.5.1.3........BO
Boot0006  USB HDD	BIOS(9,0,00)..GO..NO........i.E.x.t. .H.a.r.d. .D.i.s.k....................A.............................6..Gd-.;.A..MQ..L.2.0.1.1.0.2.1.5.0.0.0.0.0.5.7.6........BO
```

**Comment by vathpela** [comment]
How does https://github.com/vathpela/efibootmgr-devel/commit/bae00c1587b85b3d31353c0a52c845c3dc4ddb20 seem to you?

**Comment by frozencemetery** [comment]
def4bebd6cf335236c7ad3c6be3299aa444b83fc
