### ISSUE TITLE
Unparseable Boot001_BbsIndex variables

### ISSUE THREAD

**Issue by hmeine** [rhboot/efibootmgr#81]
As reported in #80, I am having parse errors with entries named like `Boot003_BbsIndex`. My machine is an Acer Revo RL80 and currently has six EFI boot entries (many redundant ones), two of which have a corresponding `_BbsIndex` entry.

I don't know what they're for, and what could / should be parsed out of them, but with the current efibootmgr, the problem seems to be that a parser is employed that was never intended to be able to parse these entries, and it fails completely.  With #80 merged, there would only remain warnings, but probably one should discuss also whether these entries should be skipped or parsed for real.

**Comment by vathpela** [comment]
Is there any way to know what they're actually for?

**Comment by martinezjavier** [comment]
@hmeine is this issue still present with the latest efibootmgr version ?
