### ISSUE TITLE
efibootmgr does not show inactive bootnum #34

### ISSUE THREAD

**Issue by c4pp4** [rhboot/efibootmgr#82]
#34 
> So if the issue is that there are some boot variables that are literally "Boot####-00000000-0000-0000-0000-000000000000", i.e. the GUID is all zeroes, then the reason we're not showing them is that they're in the wrong namespace, in fact a totally invalid one, and they won't work at all.

Is there a way to remove the 'zero' var?

**Comment by vathpela** [comment]
cd /sys/firmware/efi/efivars/
chattr -i Boot*-00000000-0000-0000-0000-000000000000
rm Boot*-00000000-0000-0000-0000-000000000000
