### ISSUE TITLE
EINVAL when writing to /sys/firmware/efi/efivars/

### ISSUE THREAD

**Issue by vedranf** [rhboot/efibootmgr#83]
Hello,

I've spent hours trying to find the cause/solution to this but apparently no one else encountered this. On a new Lenovo Thinkpad Carbon X1 5th with Debian Stretch, I'm trying to install grub (or rEFInd) and they call efibootmgr (v15) and it fails with error below. I have followed:

https://wiki.debian.org/InstallingDebianOn/Thinkpad/X1%20Carbon%205th%20Gen
https://wiki.debian.org/InstallingDebianOn/Thinkpad/X1%20Carbon%204thGen%20PCIe_SSD/jessie

for UEFI/BIOS settings and disabled secure boot, TPM, etc. Exact command which fails is:

# efibootmgr -c -d /dev/nvme0n1 -p 1 -w -L debian -l \EFI\debian\grubx64.efi

with strace output:

access("/sys/firmware/efi/efivars/Boot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c", F_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/sys/firmware/efi/efivars/Boot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c", O_WRONLY|O_CREAT, 0644) = 3
ioctl(3, FS_IOC_GETFLAGS, 0x7ffe903b7954) = 0
write(3, "\7\0\0\0\1\0\0\0\\\0d\0e\0b\0i\0a\0n\0\0\0\4\1*\0\1\0\0\0\0\10\0\0\0\0\0\0\0 \10\0\0\0\0\0,b\211lB\1;C\205\221ye\265\332\255\22\2\2\4\4.\0E\0F\0I\0d\0e\0b\0i\0a\0n\0g\0r\0u\0b\0x\0006\0004\0.\0e\0f\0i\0\0\0\177\377\4\0", 116) = -1 EINVAL (Invalid argument)
ioctl(3, FS_IOC_GETFLAGS, 0x7ffe903b7954) = 0
unlink("/sys/firmware/efi/efivars/Boot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c") = 0
close(3)                                = 0
write(2, "Could not prepare Boot variable", 31Could not prepare Boot variable) = 31

Any ideas are welcome.

Thanks,
Vedran

**Comment by mikeshultz** [comment]
Seeing the same with archlinux: 

    # efibootmgr -c -d /dev/nvme0n1 -p 1 -w -L grub -l "\EFI\grub\grubx64.efi"
    Could not prepare Boot variable: Invalid argument

**Comment by smlu** [comment]
I had also experienced this issue while installing kubuntu. For me the solution was to temporary set kernel boot parameter `efi_no_storage_paranoia`.

See also: https://wiki.archlinux.org/index.php/Unified_Extensible_Firmware_Interface#Requirements_for_UEFI_variable_support

**Comment by martinezjavier** [comment]
This should be a problem in either the kernel or the firmware, but not in efibootmgr. I'm closing this, feel free to re-open if you think that's not the case.
