### ISSUE TITLE
Could not prepare Boot variable: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by superlikex** [rhboot/efibootmgr#84]
When I install Centos7.4 using UEFI mode, it failed. The error message is : 

> The following error occurred while installing the boot loader.
The system will not be bootable.Would you like to ignores this
and continue with installation?
failed to set new efi boot target. This is most likely a kernel bug.

The detail message from log is:

> Runing... efibootmgr -c -w -L CentOS -d /dev/sda -p1 -l \EFI\centos\shimx64.efi
Could not prepare Boot variable: Inappropriate ioctl for device

what reason may casue this situation?

**Comment by martinezjavier** [comment]
This should be a problem in kernel and not in efibootmgr. I'm closing this, feel free to re-open if you think that's not the case.
