### ISSUE TITLE
Latest efibootmgr creates invalid boot entries without disk information

### ISSUE THREAD

**Issue by manni83** [rhboot/efibootmgr#85]
On one system that we use we have discovered an issue when working with newer version of efibootmgr/efivar. There the created boot entries do not include the disk information and don't work. However, older versions seem to work fine on the same system.

The first example tries to add a new boot entry `OEL2` with the newest version from master branch:

    # efibootmgr --version
    version 15
    # efibootmgr -c -d /dev/sda -p 2 -L "OEL2" -l "\efi\boot\bootx64.efi"
    # efibootmgr -v
    Skipping unreadable variable "Boot0005": Input/output error
    BootCurrent: 0008
    Timeout: 1 seconds
    BootOrder: 0000,0008,0002,0005
    Boot0000* OEL2	File(\efi\boot\bootx64.efi)
    Boot0002  Hard Drive	BBS(HD,,0x0)/VenHw(5ce8128b-2cec-40f0-8372-80640e3dc858,0200)..GO..NO..........S.A.T.A.D.O.M.-.M.L. .3.I.E.4...................\.,.@.r.d.=.X..........A...........................>..Gd-.;.A..MQ..L.0.B.2.0.7.1.2.1.2.2.1.0.0.1.0.0. .1. . ........BO
    Boot0008* OEL1	HD(1,GPT,d9e77e77-9052-467e-991a-d29ae126b2f4,0x800,0x40000)/File(\EFI\BOOT\BOOTX64.EFI)

This is the output of the old version on the same system:

    # /efibootmgr --version
    version 0.12
    # efibootmgr -c -d /dev/sda -p 2 -L "OEL2" -l "\efi\boot\bootx64.efi"
    # efibootmgr -v
    Skipping unreadable variable "Boot0005": Input/output error
    BootCurrent: 0008
    Timeout: 1 seconds
    BootOrder: 0000,0008,0002,0005
    Boot0000* OEL2	HD(2,GPT,6976becc-ea67-4fd3-ae81-4f21d62a54de,0x40800,0x40000)/File(\efi\boot\bootx64.efi)
    Boot0002  Hard Drive	BBS(HD,,0x0)/VenHw(5ce8128b-2cec-40f0-8372-80640e3dc858,0200)..GO..NO..........S.A.T.A.D.O.M.-.M.L. .3.I.E.4...................\.,.@.r.d.=.X..........A...........................>..Gd-.;.A..MQ..L.0.B.2.0.7.1.2.1.2.2.1.0.0.1.0.0. .1. . ........BO
    Boot0008* OEL1	HD(1,GPT,d9e77e77-9052-467e-991a-d29ae126b2f4,0x800,0x40000)/File(\EFI\BOOT\BOOTX64.EFI)

With the newest efibootmgr version the `Boot0000` entry does not have the disk information `HD(2,GPT,6976becc-ea67-4fd3-ae81-4f21d62a54de,0x40800,0x40000)`.

Our kernel version is:

    # uname -a
    Linux XX255I 4.9.68-rt60 #39 SMP PREEMPT RT Mon Feb 12 11:12:11 CET 2018 x86_64 GNU/Linux

Do you have any idea what might go wrong here?

Thanks,
Manfred

**Comment by martinezjavier** [comment]
Is this issue still present with the latest 17 release ?
