### ISSUE TITLE
Does efibootmgr support edit boot entry of a disk image file?

### ISSUE THREAD

**Issue by hanlz** [rhboot/efibootmgr#98]
Hi, when I try to edit the boot options of a disk image file, the parameter '--disk' does not performed to edit the image. The image file created by dd and partitioned with gdisk, then it formatted with mkfs and copied a Linux kernel file that configurated as a EFI stub into the vfat partition so I tried to set initrd= option.
I wondering whether the efibootmgr would consider to support this function, or it should use a bootloader like GRUB in this case?

Thanks in advanced.

**Comment by vathpela** [comment]
I don't understand what this is asking for - it seems like you're trying to change the boot settings in some disk image you're creating.  efibootmgr changes the firmware settings of a machine it's running on; it doesn't know anything about making or modifying boot images.
